version: "3.8"

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=P@ssw0rd
    depends_on:
      - postgres
   
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: zhuxiang1212@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
    ports:
      - 8091:80
    depends_on:
      - postgres 
